//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCarApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSPECCIONES
    {
        public int ID_INSPECCION { get; set; }
        public int ID_VEHICULO { get; set; }
        public int ID_CLIENTE { get; set; }
        public bool RALLADURAS { get; set; }
        public double CANTIDAD_COMBUSTIBLE { get; set; }
        public bool GOMA_RESPUESTA { get; set; }
        public bool GATO { get; set; }
        public bool ROTURAS_CRISTAL { get; set; }
        public bool E_G1 { get; set; }
        public bool E_G2 { get; set; }
        public bool E_G3 { get; set; }
        public bool E_G4 { get; set; }
        public System.DateTime FECHA { get; set; }
        public int ID_EMPLEADO { get; set; }
        public string ESTADO { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual VEHICULOS VEHICULOS { get; set; }
    }
}
