//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCarApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RENTA
    {
        public int NO_RENTA { get; set; }
        public int ID_EMPLEADO { get; set; }
        public int ID_VEHICULO { get; set; }
        public int ID_CLIENTE { get; set; }
        public System.DateTime FECHA_RENTA { get; set; }
        public Nullable<System.DateTime> FEHCA_DEVOLUCION { get; set; }
        public decimal MONTO_DIA { get; set; }
        public int CANTIDAD_DIAS { get; set; }
        public string COMENTARIO { get; set; }
        public string ESTADO { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual VEHICULOS VEHICULOS { get; set; }
    }
}
